<a href="https://colab.research.google.com/github/Suvanga/ML_DL/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Pytorch Fundamentals
Resources: https://www.learnpytorch.io/

Discussion Board : https://github.com/mrdbourke/pytorch-deep-learning/discussions/1284

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
# resources :!nvidia-smi

#Creating tensors


**Creation (The Builders):**
torch.tensor(): Creates a tensor from data (like a Python list).

torch.zeros() / torch.ones(): Generates tensors filled with 0s or 1s (useful for initializing weights or masks).

torch.rand(): Creates a tensor with random numbers (essential for starting training).







**Reshaping (The Organizers):**
tensor.view() / torch.reshape(): Changes the dimensions of your data without changing the data itself (e.g., flattening an image).

torch.cat(): Joins two tensors together.

tensor.permute(): Rearranges dimensions (e.g., swapping rows and columns).







**Math & Compute (The Calculators):**
torch.matmul(): Performs matrix multiplication, the engine behind nearly all neural networks.

tensor.to(): Moves your tensor to the GPU (e.g., .to('cuda')) for faster processing.

tensor.item(): Extracts a single standard Python number from a one-element tensor.




In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensors
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random Tensors

Random tensors are important because the way neural netwoeks learn is that they sttart with tendsasors full of random numbers and then adjust those random numbers to better represent the data.
##Neural Networks
####Start with random nunbers -> Look at the data -> update random numbers ->Look at the data -> Update random numbers

In [ ]:
randditensors =  torch.rand(10,10 )
randditensors

tensor([[0.6609, 0.8802, 0.4651, 0.6437, 0.0022, 0.1624, 0.5983, 0.9562, 0.8080,
         0.5968],
        [0.4424, 0.2900, 0.9742, 0.4522, 0.2656, 0.1447, 0.9934, 0.3802, 0.4650,
         0.0575],
        [0.5259, 0.3470, 0.4697, 0.3441, 0.1602, 0.9533, 0.9866, 0.7364, 0.0974,
         0.7479],
        [0.1859, 0.7088, 0.1930, 0.4519, 0.7403, 0.4315, 0.6033, 0.7006, 0.8309,
         0.6500],
        [0.2363, 0.2509, 0.7639, 0.2584, 0.7459, 0.1382, 0.9735, 0.1338, 0.9185,
         0.0493],
        [0.3230, 0.8547, 0.7225, 0.4499, 0.2707, 0.5651, 0.4013, 0.2262, 0.5911,
         0.3572],
        [0.0265, 0.1597, 0.9978, 0.5919, 0.1392, 0.7271, 0.5458, 0.9567, 0.8083,
         0.0885],
        [0.1926, 0.0202, 0.5229, 0.3479, 0.9824, 0.0225, 0.9613, 0.9214, 0.7501,
         0.4763],
        [0.5758, 0.2498, 0.8642, 0.2392, 0.9750, 0.3343, 0.2642, 0.3648, 0.7188,
         0.7248],
        [0.2401, 0.8507, 0.5576, 0.0312, 0.7179, 0.3827, 0.4454, 0.7814, 0.0898,
         0.9526]])

In [ ]:
randditensors.ndim

2

In [ ]:
random_image_tensor= torch.rand(size = (224,224,3))#height, wifth, colour channel RGB
random_image_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_tensor.ndim

3

In [ ]:
ones = torch.ones(3,3)

In [ ]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##tensor defaultly creates the float 32 values

In [ ]:
ekdekhidas = torch.arange(1,11,1)
ekdekhidas

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sunna = torch.zeros_like(input = ekdekhidas)
sunna

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32 = torch.tensor([5.0,2.0,3.0], dtype= None, device = None, requires_grad = False)
#whether or not to track gradients with this tensors operation ##)


In [ ]:
float_32.dtype

torch.float32

##The 3 major errors which we will run into when using pytorch and  DL is
Tensors are not of right:

*   Data Type
*   Device
*   Shape

When it comes to certain numerical calcuation which requires GPU and CPU interactrion in terms of data we use a third party gateway sodtware known as Cuda to make the progress happen faster


In [ ]:
FL16 = float_32.type(torch.float16)

In [ ]:
FL16

tensor([5., 2., 3.], dtype=torch.float16)

In [ ]:
FL16*float_32

tensor([25.,  4.,  9.])

##Getting some information from the tensors attributes



1.   Datatype tensor.dtype
2.   List item tensor.shape
3.   Right Device tensor.device



In [ ]:
sTensor = torch.rand(4,5)

In [ ]:
sTensor

tensor([[0.8226, 0.0187, 0.3951, 0.0259, 0.9225],
        [0.3408, 0.5687, 0.0623, 0.2766, 0.6492],
        [0.2937, 0.4379, 0.4063, 0.2935, 0.4747],
        [0.0241, 0.0238, 0.4330, 0.8118, 0.4812]])

#finding the details


In [ ]:
print("checking the data type",sTensor.dtype)
print("checking the tensor's shape attribute", sTensor.shape) #we can also use sTensor.size()
print("Checking if the tensor is in CPU or the GPU", sTensor.device)

checking the data type torch.float32
checking the tensor's shape attribute torch.Size([4, 5])
Checking if the tensor is in CPU or the GPU cpu


In [ ]:
randomNumber = torch.rand([1,11])

In [ ]:
print(randomNumber.dtype)
print(randomNumber.shape)
print(randomNumber.device)


torch.float32
torch.Size([1, 11])
cpu


In [ ]:
#Adding the Tensor

In [ ]:
tensor = torch.tensor([[1,2],[1,2]], dtype=torch.float32)

In [ ]:
print(tensor * 12)
print(tensor/10)
print(tensor+12)
print(tensor-1)



tensor([[12., 24.],
        [12., 24.]])
tensor([[0.1000, 0.2000],
        [0.1000, 0.2000]])
tensor([[13., 14.],
        [13., 14.]])
tensor([[0., 1.],
        [0., 1.]])


In [ ]:
tensor2 = torch.Tensor([[2,3],[3,4]])

In [ ]:
print(torch.matmul(tensor,tensor2))

tensor([[ 8., 11.],
        [ 8., 11.]])


In [ ]:
tensor2.ndim

2