<a href="https://colab.research.google.com/github/Suvanga/ML_DL/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Useful Links:
* PyTorch reshape: https://pytorch.org/docs/stable/gener...
* PyTorch view: https://pytorch.org/docs/stable/gener...
* PyTorch stack: https://pytorch.org/docs/stable/gener...
* PyTorch squeeze: https://pytorch.org/docs/stable/gener...
* PyTorch unsqueeze: https://pytorch.org/docs/stable/gener...
* PyTorch permute: https://pytorch.org/docs/stable/gener.




In [10]:
import torch

x = torch.arange(1.0,10.0)

# Reshaping
* for reshaping the number of tensor always needs to be same after the dimension multiplication for example x has 9 dimension so the possible reshaping can be (1,9), (9,1) and (3,3)


In [11]:
x_reshape = x.reshape(1,9)
x_reshape
#

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
x = torch.arange(1.0,13.0)
x.reshape(3,4)


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [36]:
#view
# if we change z or x it wilol always be changed on both the tensors because they use the same memory
#example
z = x.view(1,12)
z, z.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [37]:
# z.reshape(4,3)

In [38]:
x[3] =100

In [39]:
z

tensor([[  1.,   2.,   3., 100.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]])

In [40]:
z[:,0] = 1000


In [41]:
x #this changes as well it is vice versa

tensor([1000.,    2.,    3.,  100.,    5.,    6.,    7.,    8.,    9.,   10.,
          11.,   12.])

In [42]:
x.reshape

<function Tensor.reshape>